---
title: "Two-Day Dyadic Data Analysis Workshop Schedule"
output:
  pdf_document: default
  html_document: default
---

#Workshop Schedule 
##January, 2017
##Instructor: Randi L. Garcia

***

###Day 1:  Definitions, Restructuring, and The Actor-Partner Interdependence Model  

  + Lecture and Lab 9-12 and 1:00-4:00  
    - Definitions  
    - [Introduction to the Acitelli Dataset, Data Structures, and Restructuring](Day_1-Data_Restructuring.html)  
    - Nonindependence  
    - [Multilevel modeling for dyadic data](Day_1-MLM_for_Dyadic_Data.html)  
    
> Lunch 12:00 PM to 1:00 PM  

  - [Introduction to the APIM](Day_1-Actor-Partner_Interdependence_Model.html)   
    - Indistinguishable Dyads  
    - Distinguishable Dyads  
    - [Test of Distinguishability](Day_1-Test_for_Distinguishability.html)  
  - Binary Outcomes in the APIM
    - [Using Generalized Mixed Modeling](Day_1-Generalized_Linear_Mixed_Models.html)
    - Using Generalized Estimating Equations  
  + Late Afternoon Session 4:00-5:00  
    - Homework (optional)  
    - Restructure, Wok on Own Data, Individual Meetings  

***

###Day 2: Moderation, Mediation, and Over-time Models  

  + Lecture and Lab 9-12 and 1:00-4:00  
    - [Mediation in the APIM](Day_2-Mediation_in_the_APIM.html)  
    - [Moderation in the APIM](Day_2-Moderation_in_the_APIM.html) 
  
> Lunch 12:00 PM tp 1:00 PM  
  
  - [Growth Curve Models](Day_2-Growth_Curve_Modeling.html) 
    - Individual Growth Curve  
    - Dyadic Growth Curves  
  - [Stability-Influence Model](Day_2-Stability-Influence_Model.html)  
  - [Other Dyadic Models](Day_2-Common_Fate_Model.html)   
  + Late Afternoon Session 4:00-5:00  
    - Homework (optional)  
    - Wok on Own Data, Individual Meetings  
    
***

