REGRESSION
  /STATISTICS COEFF OUTS R ANOVA
  /DEPENDENT Satisfaction_H
  /METHOD=ENTER OtherPos_H OtherPos_W.

REGRESSION
  /STATISTICS COEFF OUTS R ANOVA
  /DEPENDENT Satisfaction_W
  /METHOD=ENTER OtherPos_H OtherPos_W.

