---
title: 'Day 1: Data Restructuring'
output:
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

[Back to schedule](schedule.html)

***

#Importing the Acitelli dataset into R.

```{r}
acitelli_ind <- read.csv(file.choose(), header=TRUE)

#Note that you can also specify the file path.
#acitelli_ind <- read.csv("C:/Desktop/Workshop Materials/Data/acitelli individual.csv", header=TRUE)

head(acitelli_ind)

#use this function call if you want to look at ALL of the data, or simply click on the data in your R environment
#View(acitelli_ind) 
```



We ultimately want to get our data into the pairwise format for the APIM. We'll need some more packages.

```{r}
#install.packages("tidyr")
#install.packages("dplyr")

library(tidyr)
library(dplyr)
```



##Individual to Dyad Structure

```{r}
acitelli_dyd <- acitelli_ind %>% 
  mutate(gender = ifelse(gender == 1, "H", "W")) %>%
  gather(variable, value, self_pos:simhob) %>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

head(acitelli_dyd)
```



##Individual to Pairwise Structure

```{r}
tempA <- acitelli_ind %>% 
  mutate(genderE = gender, partnum = 1) %>%
  mutate(gender = ifelse(gender == 1, "A", "P")) %>%
  gather(variable, value, self_pos:genderE) %>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

tempB <- acitelli_ind %>% 
  mutate(genderE = gender, partnum = 2) %>%
  mutate(gender = ifelse(gender == 1, "P", "A")) %>%
  gather(variable, value, self_pos:genderE)%>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

acitelli_pair <- bind_rows(tempA, tempB) %>%
  arrange(cuplid) 
  
rm(tempA, tempB)
head(acitelli_pair)
```

***

#[Dave's Kenny's handy dandy restructuring apps](http://davidakenny.net/RDDD.htm)

***

[Back to schedule](schedule.html)