---
title: "Day 1: Generalized Linear Mixed Models"
output:
  html_document: default
  html_notebook: default
---
Read in the individual data (or a pairwise dataset) 

```{r}
library(tidyr)
library(dplyr)

#install.packages("lme4")
library(lme4)

acitelli_ind <- read.csv(file.choose(), header=TRUE)
```

Convert individual data to pairwise. I also create a simhobs variable that will be our binary response. 

```{r}
tempA <- acitelli_ind %>% 
  mutate(genderE = gender, partnum = 1) %>%
  mutate(gender = ifelse(gender == 1, "A", "P")) %>%
  gather(variable, value, self_pos:genderE) %>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

tempB <- acitelli_ind %>% 
  mutate(genderE = gender, partnum = 2) %>%
  mutate(gender = ifelse(gender == 1, "P", "A")) %>%
  gather(variable, value, self_pos:genderE)%>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

acitelli_pair <- bind_rows(tempA, tempB) %>%
  arrange(cuplid) %>%
  mutate(gender_A = ifelse(genderE_A == 1, "hus", "wife"), 
         gender_A = as.factor(gender_A),
         simhob_bin_A = ifelse(simhob_A == 1, 1, 0),
         man = ifelse(genderE_A == 1, 1, 0),
         woman = ifelse(genderE_A == 1, 0, 1)) 
  
rm(tempA, tempB)
```


```{r}
apim_bin <- glmer(simhob_bin_A ~ other_pos_A + other_pos_P 
                  + (1|cuplid),
                  data = acitelli_pair,
                  family = binomial,
                  na.action = na.omit)

summary(apim_bin)
```

```{r}
apim_bin_di <- glmer(simhob_bin_A ~ other_pos_A + other_pos_P + genderE_A 
                     + other_pos_A*genderE_A + other_pos_P*genderE_A 
                     + (man + woman - 1|cuplid),
                     data = acitelli_pair,
                     family = binomial,
                     na.action = na.omit)

summary(apim_bin_di)
```


```{r}
apim_bin_di_two <- glmer(simhob_bin_A ~ gender_A + other_pos_A:gender_A + other_pos_P:gender_A - 1
                         + (man + woman - 1|cuplid),
                         data = acitelli_pair,
                         family = binomial,
                         na.action = na.omit)

summary(apim_bin_di_two)
```





